Csu 293 students past experiences
fourkitchens/s4-shared-components pull request #6
Opened 2023-06-07 06:20 UTC by AnaBZC

## Purpose:
- Description of PR

### Ticket(s)
[CSU-XX](https://fourkitchens.clickup.com/t/36718269/CSU-XX)

### Pull Request Deployment:
- Normal deployment process (`npm run rebuild` on local and ci on github)

### Functional Testing:
- [ ] Step 1
- [ ] Step 2
- [ ] Step 3
- [ ] ...

### Notes:
_Additional notes_

2023-06-09 04:31 UTC, cienvaras requested changes
Please check code comments.

2023-06-09 04:31 UTC, cienvaras commented on src/components/02-components/card-pending-task/card-pending-task.tsx
> +      <Button sx={buttonStyles} href="/opportunity">
This link shouldn't be hardcoded. Use a prop for it. Also, need to pass the `Link` component defined in `src/components/01-elements` as the value  for the `component` prop.

2023-06-09 04:31 UTC, cienvaras commented on src/components/02-components/card-pending-task/card-pending-task.tsx
> +export default function CardPendingTask() {
Please rename this to `CardPendingTasks` and the file to `card-pending-tasks`.

2023-06-09 04:31 UTC, cienvaras commented on src/components/02-components/past-experiences-page/past-experiences-page.tsx
> +export default function PastExpericiencesPage({
This is not a full page, only a component within a page. Change the name to `PastExperiencesList` (and the filename accordingly.)

2023-06-09 04:31 UTC, cienvaras commented on src/components/02-components/past-experiences-page/past-experiences-page.tsx
> +  }>;
Change this to:

```
experienceInfo: { experience: string; status: string; }[]

2023-06-09 04:31 UTC, cienvaras commented on src/components/02-components/past-experiences-page/past-experiences-page.tsx
> +import {
The table should be an individual component, don't include the pending tasks card as part of it.

2023-06-09 04:31 UTC, cienvaras commented on src/components/02-components/past-experiences-page/past-experiences-page.tsx
> +        <Link href="/experiences" sx={linkStyle}>
This link shouldn't be hardcoded. Use a prop for it. Also, need to pass the `Link` component defined in `src/components/01-elements` as the value for the `component` prop.

2023-06-19 16:56 UTC, cienvaras requested changes
Please see code comments.

2023-06-19 16:56 UTC, cienvaras commented on src/components/02-components/card-pending-tasks/card-pending-tasks.stories.tsx
> +    <Box maxWidth={'400px'}>
Remember, when the value is a literal, use `""` instead of `{''}`

```
<Box maxWidth="400px">
```

2023-06-19 16:56 UTC, cienvaras commented on src/components/02-components/card-pending-tasks/card-pending-tasks.tsx
> +import { useTheme } from '@mui/material/styles';
Please change this to

```
import { useTheme } from '@mui/material';
```

There's a bug when the theme is important in the other way.

2023-06-19 16:56 UTC, cienvaras commented on src/components/02-components/main-content/main-content.tsx
> +    maxWidth: '100vw',
Why are you adding this? This rule can be problematic in some cases.

2023-06-19 16:56 UTC, cienvaras commented on src/components/02-components/past-experiences-list/past-experiences-list.stories.tsx
> +  args: {
You're not passing a value for the `ctaLink` prop.

2023-06-19 16:56 UTC, cienvaras commented on src/components/02-components/past-experiences-list/past-experiences-list.tsx
> +  };
I don't think this is necessary. This should be added only when setting up the component in the Remix app.

2023-06-19 16:56 UTC, cienvaras commented on src/components/02-components/card-pending-tasks/card-pending-tasks.tsx
> +    flexBasis: '20%',
I don't think this `flexBasis` should be here. This should be added only when setting up the component in the Remix app.

2023-06-19 23:06 UTC, AnaBZC commented
@cienvaras this is ready for re-review

2023-07-10 16:37 UTC, cienvaras approved these changes
fixed a couple of minor things, but looks great 🚀

2023-07-10 16:40 UTC, merged